C     This File is Automatically generated by ALOHA 
C     

      SUBROUTINE SUMV3(C0, W0,C1, W1,C2, W2,WOUT)
      DOUBLE COMPLEX WOUT(18)
      DOUBLE COMPLEX C0,C1,C2
      DOUBLE COMPLEX W0(18),W1(18),W2(18)
      INTEGER I

      WOUT(5) = W0(5)
      WOUT(6) = W0(6)
      DO I= 1,4
        WOUT(I) = C0 * W0(I)+C1 * W1(I)+C2 * W2(I)
      ENDDO
      END

