C     This File is Automatically generated by ALOHA 
C     

      SUBROUTINE SUMV5(C0, W0,C1, W1,C2, W2,C3, W3,C4, W4,WOUT)
      DOUBLE COMPLEX WOUT(18)
      DOUBLE COMPLEX C0,C1,C2,C3,C4
      DOUBLE COMPLEX W0(18),W1(18),W2(18),W3(18),W4(18)
      INTEGER I

      WOUT(5) = W0(5)
      WOUT(6) = W0(6)
      DO I= 1,4
        WOUT(I) = C0 * W0(I)+C1 * W1(I)+C2 * W2(I)+C3 * W3(I)
     $   +C4 * W4(I)
      ENDDO
      END

