C     This File is Automatically generated by ALOHA 
C     

      SUBROUTINE SUMV2(C0, W0,C1, W1,WOUT)
      DOUBLE COMPLEX WOUT(18)
      DOUBLE COMPLEX C0,C1
      DOUBLE COMPLEX W0(18),W1(18)
      INTEGER I

      WOUT(5) = W0(5)
      WOUT(6) = W0(6)
      DO I= 1,4
        WOUT(I) = C0 * W0(I)+C1 * W1(I)
      ENDDO
      END

