ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G,alfas
      COMMON/STRONG/ G,alfas

c      DOUBLE COMPLEX GAL(2)
c      COMMON/WEAK/ GAL

c      DOUBLE PRECISION MB,MH,MT,MW,MTA,MZ
c      COMMON/MASSES/ MB,MH,MT,MW,MTA,MZ

c      DOUBLE PRECISION WW,WT,WZ,WH
c      COMMON/WIDTHS/ WW,WT,WZ,WH

      DOUBLE COMPLEX GC_9, GC_11, GC_4, GC_6, GC_2, GC_3, GC_5
      COMMON/COUPLINGS/ GC_9, GC_11, GC_4, GC_6, GC_2, GC_3, GC_5

