      integer icf_perch1(6)
      integer icf_perch2(10)
      integer icf_perch3(10)
      integer icf_perch4(4)
      data icf_perch1 /  1,  2,  4,  5,  6,  7 /
      data icf_perch2 /  1,  2,  3,  4,  5,  6,  7,  8,  9, 10 /
      data icf_perch4 / 3, 8, 9,10 /

      integer icf_optch1(4)
      integer icf_optch2(8)
      integer icf_optch3(10)
      integer icf_optch4(4)
      data icf_optch1 /  1,  2,  4,  5 /
      data icf_optch2 /  1,  2,  3,  4,  5,  6,  7,  8 /
      data icf_optch4 / 3, 6, 7, 8 /