      COMPLEX*16 FUNCTION FLOW2(P,NHEL,IP)
C     
C     Generated by MadGraph 5 v. 1.4.1, 2012-06-02
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     Returns color ordered amplitude for color flow 1
C     for the point with external momenta P(0:3, NEXTERNAL)
C     
C     Process: g g > g g g QCD=3 QED=0 WEIGHTED=3 singlet_QCD=0
C     
      IMPLICIT NONE

      INCLUDE 'coupl.inc'
      include 'cparam.inc'
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=15)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS
      PARAMETER (NWAVEFUNCS=10)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1, ONE
      PARAMETER (IMAG1=(0D0,1D0),ONE=(1D0,0D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL),IP(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,IC(NEXTERNAL)
      COMPLEX*16 AMP(NGRAPHS), JAMP(1)
      COMPLEX*16 W(18,NWAVEFUNCS)
      common /w/w
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DATA IC/-1,-1,1,1,1/
C
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,IP(1)),ZERO,NHEL(IP(1)),1*IC(IP(1)),W(1,1))
      CALL VXXXXX(P(0,IP(2)),ZERO,NHEL(IP(2)),1*IC(IP(2)),W(1,2))
      CALL VXXXXX(P(0,IP(3)),ZERO,NHEL(IP(3)),1*IC(IP(3)),W(1,3))
      CALL VXXXXX(P(0,IP(4)),ZERO,NHEL(IP(4)),1*IC(IP(4)),W(1,4))
      CALL VXXXXX(P(0,IP(5)),ZERO,NHEL(IP(5)),1*IC(IP(5)),W(1,5))

c$$$      CALL VXXXXX(P(0,1),ZERO,NHEL(1),1*IC(1),W(1,1))
c$$$      CALL VXXXXX(P(0,2),ZERO,NHEL(2),1*IC(2),W(1,2))
c$$$      CALL VXXXXX(P(0,3),ZERO,NHEL(3),1*IC(3),W(1,3))
c$$$      CALL VXXXXX(P(0,4),ZERO,NHEL(4),1*IC(4),W(1,4))
c$$$      CALL VXXXXX(P(0,5),ZERO,NHEL(5),1*IC(5),W(1,5))

c      Call wavsort(next,floworder(1,1),W)
c      write(luerr,*) floworder
 
      CALL VVV1_1(W(1,4),W(1,3),GC_4,ZERO, ZERO, W(1,6))
      CALL VVV1_1(W(1,2),W(1,1),GC_4,ZERO, ZERO, W(1,7))
      CALL VVV1_1(W(1,5),W(1,4),GC_4,ZERO, ZERO, W(1,8))
      CALL VVV1_1(W(1,3),W(1,2),GC_4,ZERO, ZERO, W(1,9))
      CALL VVV1_1(W(1,5),W(1,1),GC_4,ZERO, ZERO, W(1,10))
C     Amplitude(s) for diagram number 1
      CALL VVV1_0(W(1,5),W(1,6),W(1,7),GC_4,AMP(1))
C     Amplitude(s) for diagram number 2
      CALL VVV1_0(W(1,8),W(1,3),W(1,7),GC_4,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL VVVV1_0(W(1,5),W(1,4),W(1,3),W(1,7),GC_6,AMP(3))
      CALL VVVV4_0(W(1,5),W(1,4),W(1,3),W(1,7),GC_6,AMP(4))
C     Amplitude(s) for diagram number 4
      CALL VVV1_0(W(1,4),W(1,9),W(1,10),GC_4,AMP(5))
C     Amplitude(s) for diagram number 5
      CALL VVV1_0(W(1,6),W(1,2),W(1,10),GC_4,AMP(6))
C     Amplitude(s) for diagram number 6
      CALL VVVV1_0(W(1,4),W(1,3),W(1,2),W(1,10),GC_6,AMP(7))
      CALL VVVV4_0(W(1,4),W(1,3),W(1,2),W(1,10),GC_6,AMP(8))
C     Amplitude(s) for diagram number 7
      CALL VVV1_0(W(1,8),W(1,9),W(1,1),GC_4,AMP(9))
C     Amplitude(s) for diagram number 8
      CALL VVVV1_0(W(1,8),W(1,3),W(1,2),W(1,1),GC_6,AMP(10))
      CALL VVVV4_0(W(1,8),W(1,3),W(1,2),W(1,1),GC_6,AMP(11))
C     Amplitude(s) for diagram number 9
      CALL VVVV1_0(W(1,5),W(1,6),W(1,2),W(1,1),GC_6,AMP(12))
      CALL VVVV4_0(W(1,5),W(1,6),W(1,2),W(1,1),GC_6,AMP(13))
C     Amplitude(s) for diagram number 10
      CALL VVVV1_0(W(1,5),W(1,4),W(1,9),W(1,1),GC_6,AMP(14))
      CALL VVVV4_0(W(1,5),W(1,4),W(1,9),W(1,1),GC_6,AMP(15))
      JAMP(1)=+2*(-IMAG1*AMP(1)-IMAG1*AMP(2)-IMAG1*AMP(3)+IMAG1*AMP(4)
     $ +IMAG1*AMP(5)+IMAG1*AMP(6)+IMAG1*AMP(7)-IMAG1*AMP(8)-IMAG1
     $ *AMP(9)-IMAG1*AMP(10)+IMAG1*AMP(11)-IMAG1*AMP(12)+IMAG1*AMP(13)
     $ -IMAG1*AMP(14)+IMAG1*AMP(15))

      FLOW2=JAMP(1)
      RETURN
      END

