      COMPLEX*16 FUNCTION FLOW1(P,NHEL,IP)
C     
C     Generated by MadGraph 5 v. 1.4.1, 2012-06-02
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     Returns color ordered amplitude for color flow 1
C     for the point with external momenta P(0:3, NEXTERNAL)
C     
C     Process: g g > g g g g QCD=4 QED=0 WEIGHTED=4 singlet_QCD=0
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=32)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS
      PARAMETER (NWAVEFUNCS=27)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1, ONE
      PARAMETER (IMAG1=(0D0,1D0),ONE=(1D0,0D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL),IP(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,IC(NEXTERNAL)
      COMPLEX*16 AMP(NGRAPHS), JAMP(1)
      COMPLEX*16 W(18,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DATA IC/-1,-1,1,1,1,1/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,IP(1)),ZERO,NHEL(IP(1)),1*IC(IP(1)),W(1,1))
      CALL VXXXXX(P(0,IP(2)),ZERO,NHEL(IP(2)),1*IC(IP(2)),W(1,2))
      CALL VXXXXX(P(0,IP(3)),ZERO,NHEL(IP(3)),1*IC(IP(3)),W(1,3))
      CALL VXXXXX(P(0,IP(4)),ZERO,NHEL(IP(4)),1*IC(IP(4)),W(1,4))
      CALL VXXXXX(P(0,IP(5)),ZERO,NHEL(IP(5)),1*IC(IP(5)),W(1,5))
      CALL VXXXXX(P(0,IP(6)),ZERO,NHEL(IP(6)),1*IC(IP(6)),W(1,6))
      CALL VVV1_1(W(1,4),W(1,3),GC_4,ZERO, ZERO, W(1,7))
      CALL VVV1_1(W(1,2),W(1,1),GC_4,ZERO, ZERO, W(1,8))
      CALL VVV1_1(W(1,6),W(1,5),GC_4,ZERO, ZERO, W(1,9))
      CALL VVV1_1(W(1,5),W(1,4),GC_4,ZERO, ZERO, W(1,10))
      CALL VVV1_1(W(1,3),W(1,2),GC_4,ZERO, ZERO, W(1,11))
      CALL VVV1_1(W(1,6),W(1,1),GC_4,ZERO, ZERO, W(1,12))
      CALL VVV1_1(W(1,6),W(1,8),GC_4,ZERO, ZERO, W(1,13))
      CALL VVV1_1(W(1,2),W(1,12),GC_4,ZERO, ZERO, W(1,14))
      CALL VVVV1_1(W(1,6),W(1,2),W(1,1),GC_6,ZERO, ZERO, W(1,15))
      CALL VVVV3_1(W(1,6),W(1,2),W(1,1),GC_6,ZERO, ZERO, W(1,16))
      CALL SUMV4(2.*ONE,W(1,13),2.*ONE,W(1,14),2.*ONE,W(1,15),2.
     $ *ONE,W(1,16),W(1,17))
      CALL VVV1_1(W(1,3),W(1,8),GC_4,ZERO, ZERO, W(1,18))
      CALL VVV1_1(W(1,11),W(1,1),GC_4,ZERO, ZERO, W(1,19))
      CALL VVVV1_1(W(1,3),W(1,2),W(1,1),GC_6,ZERO, ZERO, W(1,20))
      CALL VVVV4_1(W(1,3),W(1,2),W(1,1),GC_6,ZERO, ZERO, W(1,21))
      CALL SUMV4(-2.*ONE,W(1,18),-2.*ONE,W(1,19),-2.*ONE,W(1,20),2.
     $ *ONE,W(1,21),W(1,22))
      CALL VVV1_1(W(1,5),W(1,12),GC_4,ZERO, ZERO, W(1,23))
      CALL VVV1_1(W(1,9),W(1,1),GC_4,ZERO, ZERO, W(1,24))
      CALL VVVV3_1(W(1,6),W(1,5),W(1,1),GC_6,ZERO, ZERO, W(1,25))
      CALL VVVV4_1(W(1,6),W(1,5),W(1,1),GC_6,ZERO, ZERO, W(1,26))
      CALL SUMV4(-2.*ONE,W(1,23),2.*ONE,W(1,24),-2.*ONE,W(1,25),
     $ -2.*ONE,W(1,26),W(1,27))
C     Amplitude(s) for diagram number 1
      CALL VVVV1_0(W(1,6),W(1,5),W(1,7),W(1,8),GC_6,AMP(1))
      CALL VVVV4_0(W(1,6),W(1,5),W(1,7),W(1,8),GC_6,AMP(2))
C     Amplitude(s) for diagram number 2
      CALL VVV1_0(W(1,5),W(1,7),W(1,17),GC_4,AMP(3))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,9),W(1,7),W(1,8),GC_4,AMP(4))
C     Amplitude(s) for diagram number 4
      CALL VVVV1_0(W(1,6),W(1,10),W(1,3),W(1,8),GC_6,AMP(5))
      CALL VVVV4_0(W(1,6),W(1,10),W(1,3),W(1,8),GC_6,AMP(6))
C     Amplitude(s) for diagram number 5
      CALL VVV1_0(W(1,6),W(1,10),W(1,22),GC_4,AMP(7))
C     Amplitude(s) for diagram number 6
      CALL VVV1_0(W(1,10),W(1,3),W(1,17),GC_4,AMP(8))
C     Amplitude(s) for diagram number 7
      CALL VVVV1_0(W(1,9),W(1,4),W(1,3),W(1,8),GC_6,AMP(9))
      CALL VVVV4_0(W(1,9),W(1,4),W(1,3),W(1,8),GC_6,AMP(10))
C     Amplitude(s) for diagram number 8
      CALL VVV1_0(W(1,9),W(1,4),W(1,22),GC_4,AMP(11))
C     Amplitude(s) for diagram number 9
      CALL VVVV1_0(W(1,5),W(1,4),W(1,3),W(1,17),GC_6,AMP(12))
      CALL VVVV4_0(W(1,5),W(1,4),W(1,3),W(1,17),GC_6,AMP(13))
C     Amplitude(s) for diagram number 10
      CALL VVVV1_0(W(1,6),W(1,5),W(1,4),W(1,22),GC_6,AMP(14))
      CALL VVVV4_0(W(1,6),W(1,5),W(1,4),W(1,22),GC_6,AMP(15))
C     Amplitude(s) for diagram number 11
      CALL VVVV1_0(W(1,5),W(1,4),W(1,11),W(1,12),GC_6,AMP(16))
      CALL VVVV4_0(W(1,5),W(1,4),W(1,11),W(1,12),GC_6,AMP(17))
C     Amplitude(s) for diagram number 12
      CALL VVV1_0(W(1,4),W(1,11),W(1,27),GC_4,AMP(18))
C     Amplitude(s) for diagram number 13
      CALL VVV1_0(W(1,10),W(1,11),W(1,12),GC_4,AMP(19))
C     Amplitude(s) for diagram number 14
      CALL VVVV1_0(W(1,5),W(1,7),W(1,2),W(1,12),GC_6,AMP(20))
      CALL VVVV4_0(W(1,5),W(1,7),W(1,2),W(1,12),GC_6,AMP(21))
C     Amplitude(s) for diagram number 15
      CALL VVV1_0(W(1,7),W(1,2),W(1,27),GC_4,AMP(22))
C     Amplitude(s) for diagram number 16
      CALL VVVV1_0(W(1,10),W(1,3),W(1,2),W(1,12),GC_6,AMP(23))
      CALL VVVV4_0(W(1,10),W(1,3),W(1,2),W(1,12),GC_6,AMP(24))
C     Amplitude(s) for diagram number 17
      CALL VVVV1_0(W(1,4),W(1,3),W(1,2),W(1,27),GC_6,AMP(25))
      CALL VVVV4_0(W(1,4),W(1,3),W(1,2),W(1,27),GC_6,AMP(26))
C     Amplitude(s) for diagram number 18
      CALL VVVV1_0(W(1,6),W(1,10),W(1,11),W(1,1),GC_6,AMP(27))
      CALL VVVV4_0(W(1,6),W(1,10),W(1,11),W(1,1),GC_6,AMP(28))
C     Amplitude(s) for diagram number 19
      CALL VVVV1_0(W(1,9),W(1,4),W(1,11),W(1,1),GC_6,AMP(29))
      CALL VVVV4_0(W(1,9),W(1,4),W(1,11),W(1,1),GC_6,AMP(30))
C     Amplitude(s) for diagram number 20
      CALL VVVV1_0(W(1,9),W(1,7),W(1,2),W(1,1),GC_6,AMP(31))
      CALL VVVV4_0(W(1,9),W(1,7),W(1,2),W(1,1),GC_6,AMP(32))
      JAMP(1)=+2*AMP(1)-2*AMP(2)-AMP(3)+2*AMP(4)+2*AMP(5)-2*AMP(6)
     $ -AMP(7)-AMP(8)+2*AMP(9)-2*AMP(10)-AMP(11)-AMP(12)+AMP(13)
     $ -AMP(14)+AMP(15)-2*AMP(16)+2*AMP(17)-AMP(18)-2*AMP(19)
     $ -2*AMP(20)+2*AMP(21)-AMP(22)-2*AMP(23)+2*AMP(24)-AMP(25)
     $ +AMP(26)+2*AMP(27)-2*AMP(28)+2*AMP(29)-2*AMP(30)+2*AMP(31)
     $ -2*AMP(32)

      FLOW1=JAMP(1)
      RETURN
      END

