      integer icf_perch1(12)
      integer icf_perch2(24)
      integer icf_perch3(25)
      integer icf_perch4(12)
      data icf_perch1 /  1,  3,  4,  8,  9, 10, 11, 12, 13, 14
     &                , 16, 17 /
      data icf_perch2 /  1,  2,  3,  4,  5,  6,  7,  8,  9, 10
     &                , 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
     &                , 21, 22, 23, 24 /
      data icf_perch3 /  1,  2,  3,  4,  5,  6,  7,  8,  9, 10
     &                , 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
     &                , 21, 22, 23, 24, 25 /
      data icf_perch4 / 2, 5, 6, 7,15,18,19,20,21,22,23,24 /

      integer icf_optch1(6)
      integer icf_optch2(18)
      integer icf_optch3(19)
      integer icf_optch4(12)
      data icf_optch1 /  1,  3,  4,  8, 10, 11 /
      data icf_optch2 /  1,  2,  3,  4,  5,  6,  7,  8,  9, 10
     &                , 11, 12, 13, 14, 15, 16, 17, 18 /
      data icf_optch3 /  1,  2,  3,  4,  5,  6,  7,  8,  9, 10
     &                , 11, 12, 13, 14, 15, 16, 17, 18, 19 /
      data icf_optch4 / 2, 5, 6, 7, 9
     &               , 12,13,14,15,16,17,18 /