C     -------------------------
      SUBROUTINE SMATRIX_co1(ICF,P,ANS)
C     -------------------------
C     
C     Generated by MadGraph 5 v. 1.4.1, 2012-06-02
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     MadGraph StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > g g g g g QCD=5 QED=0 WEIGHTED=5 singlet_QCD=0
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX_co1
      INTEGER IHEL,IDEN, I,ICF
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./
      DATA (NHEL(I,   1),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  65),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  66),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  67),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  68),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  69),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  70),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  71),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  72),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  73),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  74),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  75),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  76),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  77),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  78),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  79),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  80),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  81),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  82),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  83),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  84),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  85),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  86),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  87),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  88),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  89),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  90),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  91),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  92),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  93),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  94),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  95),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  96),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  97),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  98),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  99),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 100),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 101),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 102),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 103),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 104),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 105),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 106),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 107),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 108),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 109),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 110),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 111),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 112),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 113),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 114),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 115),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 116),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 117),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 118),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 119),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 120),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 121),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 122),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 123),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 124),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 125),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 126),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 127),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 128),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA IDEN/30720/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL) .OR. NTRY .LT. 2) THEN
          T=MATRIX_co1(ICF,P,NHEL(1,IHEL))
          ANS=ANS+T
          IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
            GOODHEL(IHEL)=.TRUE.
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      END

C     ------------------------------
      REAL*8 FUNCTION MATRIX_co1(ICF,P,NHEL)
C     ------------------------------
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external momenta P(0:3,NEXTERNAL)
C     
C     Process: g g > g g g g g QCD=5 QED=0 WEIGHTED=5 singlet_QCD=0
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NPERMS
      PARAMETER (NPERMS=720)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,PERM(NEXTERNAL),ICF
      COMPLEX*16 ZTEMP
C     
C     EXTERNAL FUNCTIONS
C     
      COMPLEX*16 ONEPERM_co1
      EXTERNAL ONEPERM_co1

c      ZTEMP = (0.D0,0.D0)
c      DO I=1,NPERMS
        CALL GETPERM_co1(ICF,PERM)
        ZTEMP=ONEPERM_co1(P,NHEL,PERM)
c        ZTEMP=ZTEMP+ONEPERM(P,NHEL,PERM)
c      ENDDO
      MATRIX_co1=DBLE(ZTEMP)

      RETURN
      END

C     --------------------------------------
      COMPLEX*16 FUNCTION ONEPERM_co1(P,NHEL,PM)
C     --------------------------------------
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > g g g g g QCD=5 QED=0 WEIGHTED=5 singlet_QCD=0
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NFLOWS
      PARAMETER (NFLOWS=1)
      INTEGER    NPERMS
      PARAMETER (NPERMS=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER PM(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      COMPLEX*16 JAMP(NFLOWS)
      INTEGER PERMS(NEXTERNAL,NPERMS),IFERM(NPERMS),PERM(NEXTERNAL)
      DATA (PERMS(I,   1),I=1,7) / 1, 2, 3, 4, 5, 6, 7/
      DATA IFERM/ 1/
C     
C     EXTERNAL FUNCTIONS
C     
      COMPLEX*16 FLOW1
      EXTERNAL FLOW1
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     ----------
C     BEGIN CODE
C     ----------
      DO I=1,NEXTERNAL
        PERM(I)=PM(PERMS(I,1))
      ENDDO
      JAMP(1)=IFERM(1)*FLOW1(P,NHEL,PERM)
      ZTEMP = (0.D0,0.D0)
      ZTEMP = ZTEMP+1/16D0*JAMP(1)*DCONJG(243D0*(JAMP(1)))
      ONEPERM_co1=ZTEMP

      RETURN
      END

C     ------------------------------------
      SUBROUTINE GETPERM_co1(IPERM,PERM)
C     ------------------------------------
C     
C     Gives permutation number IPERM. 
C     Return value is the fermion factor due to PERM
C     
C     Process: g g > g g g g g QCD=5 QED=0 WEIGHTED=5 singlet_QCD=0
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      INTEGER IPERM,PERM(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,IFLAG
      LOGICAL OK
      INTEGER COMP(NEXTERNAL)
      DATA COMP/1,1,1,1,1,1,1/
C     ----------
C     BEGIN CODE
C     ----------
      DO I=1,NEXTERNAL
        PERM(I)=I
      ENDDO
      I=1
      DO WHILE(I.LT.IPERM)
        CALL IPNEXT(PERM,NEXTERNAL,IFLAG)
        OK=.TRUE.
        DO J=1,NEXTERNAL
          IF(COMP(PERM(J)).NE.COMP(J))THEN
            OK=.FALSE.
            EXIT
          ENDIF
        ENDDO
        IF(OK) I=I+1
      ENDDO
      END

