ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G, ALFAS
      COMMON/STRONG/ G, ALFAS

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION DUM0
      COMMON/FRDUM0/ DUM0

      DOUBLE PRECISION DUM1
      COMMON/FRDUM1/ DUM1

      DOUBLE PRECISION MB,MH,MT,MW,MTA,MZ

      COMMON/MASSES/ MB,MH,MT,MW,MTA,MZ


      DOUBLE PRECISION WW,WT,WZ,WH

      COMMON/WIDTHS/ WW,WT,WZ,WH


      DOUBLE COMPLEX GC_4, GC_6, G2, GG2, GG0

      COMMON/COUPLINGS/ GC_4, GC_6,G2, GG2, GG0

