      double precision ptcutj
      parameter (ptcutj = 20.d0)
      double precision etacutj
      parameter (etacutj = 5.d0)

      double precision ptcutb
      parameter (ptcutb = 20.d0)
      double precision etacutb
      parameter (etacutb = 2.5d0)

      double precision ptcutl
      parameter (ptcutl = 20.d0)
      double precision etacutl
      parameter (etacutl = 2.5d0)

      double precision ptcuta
      parameter (ptcuta = 20.d0)
      double precision etacuta
      parameter (etacuta = 2.5d0)

      double precision drcut
      parameter (drcut = 0.4d0)

      double precision ptjjcut
      parameter (ptjjcut = 20.d0)
