      double precision pi,twopi,fourpi,pihalf,sqrt2,sqrt3
      parameter (pi     = 3.14159265358979323846d0)
      parameter (twopi  = 2.d0*pi)
      parameter (fourpi = 4.d0*pi)
      parameter (pihalf = 0.5d0*pi)
      parameter (sqrt2  = 1.41421356237309504880d0)
      parameter (sqrt3  = 1.7320508075688772935d0)
      double precision rd2dg,dg2rd,gev2pb,gev2fb
      parameter (rd2dg  = 180.d0/pi)
      parameter (dg2rd  = pi/180.d0)
      parameter (gev2pb = 3.8937966d8)
      parameter (gev2fb = 3.8937966d11)
      double precision em,alf0,gf
      parameter (em     = 0.51099906d-3)
      parameter (alf0   = 1.d0/137.0359895d0)
      parameter (gf     = 1.16639d-5)
      double complex ci
      parameter (ci     = (0d0,1d0))